project_name: hookmsg

build:
  env:
    - CGO_ENABLED=0

  main: ./cmd/hookmsg
  binary: hookmsg
  goos:
    - linux
  goarch:
    - amd64
    - arm64

archives:
  - name_template: "{{.Os}}-{{.Arch}}-{{ .ProjectName }}"
    format: tar.gz
